[package]
name = "jupiter"
version = "0.1.0"
edition = "2024"

[dependencies]

[[example]]
name = "test"
doc-scrape-examples = true

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
