[package]
name = "draca"
version = "0.1.0"
edition = "2024"

[dependencies]
jupiter = { version = "0.1.0", path = "../jupiter" }
pest = "2.8.4"
pest_consume = "1.1.3"
pest_derive = "2.8.4"
strfmt = "0.2.5"
